---
dist: trusty
sudo: required
language: ruby
rvm:
 - 2.4.1
before_install:
  - lscpu
  - sudo apt-get update
  - sudo apt-get  install --yes qemu-system-x86 ipxe-qemu sshpass
script:
  - docker-compose up
  - qemu-system-x86_64 -kernel build/vmlinuz -initrd build/initramfs -append 'console=ttyS0 net.ifnames=0 biosdevname=0 break=skip_loading_plugins' -m 2048 -smp 2 -display none -daemonize -net user,hostfwd=tcp::2222-:22 -net nic
  - while ! nc -z 127.0.0.1 2222; do echo 'Waiting for Coinboot machine to listen on port 2222/SSH ...'; sleep 10; done
  - sleep 30
  - sshpass -p ubuntu ssh -vvvv -l ubuntu -p 2222 localhost cat /etc/motd 
