---
dist: trusty
sudo: required
language: ruby
rvm:
 - 2.4.1
before_install:
  - lscpu
  - sudo apt-get update
  - sudo apt-get -y install libvirt-bin libvirt-dev qemu-utils qemu
  - sudo systemctl restart libvirtd.service
  - wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb && sudo dpkg -i vagrant*
  - sudo vagrant plugin install vagrant-reload
  - sudo vagrant plugin install vagrant-libvirt
script:
  - sudo vagrant up make-rootfs-travisci
