---
dist: trusty
sudo: required
language: bash


jobs:
  include:
    - stage: build and run
      script: build_and_run
      env: KERNEL=4.15.0-43-generic SUITE=xenial
      deploy: &deploy
        provider: releases
        api_key: ${TOKEN}
        file_glob: true
        file: build/*
        skip_cleanup: true
        on:
          all_branches: true
        draft: true
    - script: build_and_run
      env: KERNEL=4.15.0-45-generic SUITE=xenial
      deploy: &deploy
        provider: releases
        api_key: ${TOKEN}
        file_glob: true
        file: build/*
        skip_cleanup: true
        on:
          all_branches: true
        draft: true

    - stage: publish
      deploy: &deploy
        provider: releases
        api_key: ${TOKEN}
        file_glob: true
        file: build/*
        skip_cleanup: true
        on:
          all_branches: true
        draft: false
